#!/usr/bin/env python3
"""mmdet_to_pt.py — mmdet config → backbone/neck wrapped nn.Module → .pt 저장 (CLI).

전처리 단계(= "mmdet 을 파일로 뺀다"). g2c 와 무관하게 mmdet 만 여기(vision.cpp/tools/frontend/mmdet)서
다룬다. 클래스는 mmdet_wrap.MMDetBackbone → torch.load 가 동일 클래스로 복원(pickle 모듈명 =
'mmdet_wrap'). g2c 로 이 .pt 를 컴파일할 때도 이 폴더가 PYTHONPATH 에 있어야 mmdet_wrap 를 import 함.

사용:
  # (이 폴더 = vision.cpp/tools/frontend/mmdet 을 PYTHONPATH 에)
  python mmdet_to_pt.py --config retinanet_r18_fpn_1x_coco.py --out retinanet_bb.pt --size 512
  # 이후 g2c(코어 무수정, mmdet 코드 없음)로 컴파일:
  PYTHONPATH=<GTX_Compiler>:<이 폴더> g2c --model retinanet_bb.pt --name Retina --output output/retina
"""
import argparse
import math
import os
import sys
import torch

# self-contained import: 이 파일 폴더(tools/frontend/mmdet)를 경로에 넣고 top-level 모듈로 import
# → torch.save 피클 모듈경로 = 'mmdet_wrap' (mmdet 라이브러리와 이름 충돌 없음).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mmdet_compat  # noqa: E402
from mmdet_wrap import MMDetBackbone, build   # noqa: E402,F401 (MMDetBackbone: 피클 등록)


def _f(v):
    """A C++ float literal. repr keeps the significant digits.

    Infinities reach here from configs that bound a regression range with one -- FCOS writes
    regress_ranges=((-1, 64), ..., (512, INF)) -- and `inff` is not something C++ accepts.
    """
    v = float(v)
    if math.isinf(v):
        return "-INFINITY" if v < 0 else "INFINITY"
    if math.isnan(v):
        return "NAN"
    return f"{v!r}f"


def _arr(name, values):
    return f"    c.det.{name} = {{{', '.join(_f(v) for v in values)}}};\n"


def emit_params(cfg, config_name):
    """Decoding and anchor configuration as a C++ header holding mmdet_params().

    Replaces the JSON sidecar. The values end up inside the executable, which removes a
    deployed file and makes it impossible to pair a .gguf with a configuration from a
    different export.
    """
    h = cfg.get("head_type", "raw")
    out = [
        "// Generated by mmdet_to_pt.py — do not edit.\n",
        f"// source: {config_name}\n",
        f"// head_type: {h}\n",
        "#pragma once\n\n",
        "#include <cmath>\n",
        '#include "head.h"\n\n',
        "namespace visp {\n\n",
        "inline mmdet_cfg mmdet_params() {\n",
        "    mmdet_cfg c;\n",
    ]
    if h == "raw":
        out += [
            "    // The head in this config was not recognised, so only the backbone is\n",
            "    // exported and decoding is left to the caller.\n",
            "    return c;\n}\n\n}  // namespace visp\n",
        ]
        return "".join(out)

    out.append(f"    c.head.kind = head_kind::{h};\n")
    for k in ("stacked_convs", "reg_stacked_convs", "feat_channels", "num_base",
              "num_classes", "gn_groups", "reg_max", "corner_topk", "local_max_kernel",
              "embed_dims", "n_heads", "enc_layers", "dec_layers", "n_points", "num_queries"):
        if k in cfg:
            out.append(f"    c.head.{k} = {int(cfg[k])};\n")
    for k in ("cls_convs_prefix", "reg_convs_prefix", "cls_head", "reg_head",
              "centerness_head", "scales_prefix", "per_level_head_tail", "pre_conv",
              "bbox_cls_head"):
        if k in cfg:
            out.append(f'    c.head.{k} = "{cfg[k]}";\n')
    for k in ("head_has_norm", "centerness_on_reg", "bbox_exp", "bbox_clamp_stride", "bbox_mul_stride",
          "per_level_towers", "per_level_heads", "head_silu", "ctr_tanh", "corner_emb", "corner_centripetal"):
        out.append(f"    c.head.{k} = {str(bool(cfg.get(k, False))).lower()};\n")
    # 조립기도 stride 를 쓴다(FCOS 의 곱, GFL 의 거리, TOOD 의 격자→픽셀).
    out.append("    c.head.strides = {" + ", ".join(_f(v) for v in cfg["strides"]) + "};\n")
    if cfg.get("reg_denoms"):
        out.append("    c.head.reg_denoms = {" + ", ".join(_f(v) for v in cfg["reg_denoms"]) + "};\n")
    # 격자 중심. anchor 계열(AnchorGenerator)은 0, point 계열은 0.5 — 조립기가 TOOD 에 쓴다.
    out.append(f"    c.head.head_leaky = {_f(cfg.get('head_leaky', 0.0))};\n")
    out.append("    c.head.corner_distance_thr = "
               f"{_f(cfg.get('corner_distance_thr', 0.5))};\n")
    out.append(f"    c.head.ddq_iou_thr = {_f(cfg.get('ddq_iou_thr', 0.8))};\n")
    out.append(f"    c.head.center_offset = {_f(cfg.get('center_offset', 0.0))};\n\n")

    # 임계값은 **게이트 앞**이다 — 디코더가 무엇이 되든 mmdet 의 test_cfg 를 써야 한다.
    # 안 실으면 구조체 기본값(0.05/0.5/1000/100)이 쓰이는데, ATSS 는 nms 0.6,
    # RTMDet 은 score 0.001·nms 0.65·max 300 이라 살아남는 박스 집합이 달라진다.
    out.append(f"    c.det.score_thr = {_f(cfg.get('score_thr', 0.05))};\n")
    out.append(f"    c.det.nms_thr = {_f(cfg.get('nms_thr', 0.5))};\n")
    out.append(f"    c.det.nms_pre = {int(cfg.get('nms_pre', 1000))};\n")
    out.append(f"    c.det.max_per_img = {int(cfg.get('max_per_img', 100))};\n")
    out.append(f"    c.det.min_bbox_size = {_f(cfg.get('min_bbox_size', -1.0))};\n")
    # 레벨별 앵커가 재현식으로 안 나오는 계열(SSD 는 레벨마다 개수가 다르고, YOLACT 는
    # base_size·중심을 stride 와 따로 준다). **분기 앞에** 둔다 — 디코드 가능/불가 어느
    # 쪽이든 필요하다(yolact 는 Delta 코더라 아래 분기로 가는데, 여기 없으면 안 실린다).
    if cfg.get("base_anchor_boxes"):
        for lvl in cfg["base_anchor_boxes"]:
            out.append("    c.det.base_anchor_boxes.push_back({"
                       + ", ".join(_f(v) for v in lvl) + "});\n")
        for i, v in enumerate(cfg.get("means", [0.0] * 4)):
            out.append(f"    c.det.means[{i}] = {_f(v)};\n")
        for i, v in enumerate(cfg.get("stds", [1.0] * 4)):
            out.append(f"    c.det.stds[{i}] = {_f(v)};\n")

    # anchor(Delta) 디코드가 되는 계열만 c.det 의 **앵커 파라미터**를 채운다. 조립은
    # 되는데 코더가 다른 계열(FSAF 의 TBLRBBoxCoder 등)은 head 원시 출력까지만 낸다.
    # rpn 도 **앵커 파라미터를 그대로 쓴다**(디코드만 레벨별 NMS 로 다르다) — 같이 채운다.
    if h not in ("anchor", "rpn", "yolof") or not cfg.get("can_decode", True):
        out += [
            "    // Decoding for this family is the caller's: the head above emits raw\n",
            "    // per-level tensors, and only the anchor(Delta) path fills c.det here.\n",
        ]
        out.append("    c.det.strides = {" + ", ".join(_f(v) for v in cfg["strides"]) + "};\n")
        # YOLOv3 의 (w,h) 앵커. 레벨별로 하나씩 싣는다 — 순서가 곧 레벨 순서다.
        for i, lvl in enumerate(cfg.get("base_sizes") or []):
            out.append(f"    c.det.base_sizes.push_back({{"
                       + ", ".join(_f(v) for v in lvl) + "});\n")
        if cfg.get("conf_thr"):
            out.append(f"    c.det.conf_thr = {_f(cfg['conf_thr'])};\n")
        # SABL 의 버킷 파라미터. 0 이면 안 싣는다.
        if cfg.get("num_buckets"):
            out.append(f"    c.det.num_buckets = {int(cfg['num_buckets'])};\n")
            out.append(f"    c.det.bucket_scale = {_f(cfg.get('bucket_scale', 3.0))};\n")
            out.append(f"    c.det.anchor_scale = {_f(cfg.get('anchor_scale') or 4.0)};\n")
        # FSAF(TBLR). 앵커 생성 파라미터도 같이 실어야 디코더가 앵커를 만든다.
        if cfg.get("tblr_normalizer"):
            out.append(f"    c.det.tblr_normalizer = {_f(cfg['tblr_normalizer'])};\n")
            out.append(f"    c.det.octave_base_scale = {_f(cfg.get('octave_base_scale', 1.0))};\n")
            out.append(_arr("octave_scales", cfg["octave_scales"]))
            out.append(_arr("ratios", cfg["ratios"]))
            out.append(f"    c.det.center_offset = {_f(cfg.get('center_offset', 0.0))};\n")
        # FoveaBox 만 채운다. 비어 있으면 디코더가 조립기가 낸 값을 그대로 거리로 쓴다.
        if cfg.get("bbox_base_edge"):
            out.append("    c.det.base_edge = {"
                       + ", ".join(_f(v) for v in cfg["bbox_base_edge"]) + "};\n")
        # ⚠️ `c.det.num_classes` 는 **배경을 뺀** 클래스 수다. softmax head(고전 DETR)는
        #    채널이 하나 더 많으므로(`cls_out_channels = num_classes + 1`), 채널 폭은
        #    `c.head.num_classes` 를 쓰고 여기엔 의미상 값을 싣는다. 뒤바꾸면 배경을
        #    클래스로 세거나 마지막 클래스를 잃는다.
        out.append("    c.det.num_classes = "
                   f"{int(cfg.get('num_classes_semantic', cfg.get('num_classes', 80)))};\n")
        out.append(f"    c.det.use_sigmoid = {str(bool(cfg.get('use_sigmoid', True))).lower()};\n")
        for i, v in enumerate(cfg.get("img_mean", [0.0] * 3)):
            out.append(f"    c.img_mean[{i}] = {_f(v)};\n")
        for i, v in enumerate(cfg.get("img_std", [1.0] * 3)):
            out.append(f"    c.img_std[{i}] = {_f(v)};\n")
        out.append(f"    c.to_rgb = {str(bool(cfg.get('to_rgb', False))).lower()};\n")
        out.append("    return c;\n}\n\n}  // namespace visp\n")
        return "".join(out)

    out.append(_arr("strides", cfg["strides"]))
    out.append(_arr("octave_scales", cfg["octave_scales"]))
    out.append(_arr("ratios", cfg["ratios"]))
    out.append(f"    c.det.octave_base_scale = {_f(cfg.get('octave_base_scale', 4.0))};\n")
    out.append(f"    c.det.center_offset = {_f(cfg.get('center_offset', 0.0))};\n")
    for i, v in enumerate(cfg.get("means", [0.0] * 4)):
        out.append(f"    c.det.means[{i}] = {_f(v)};\n")
    for i, v in enumerate(cfg.get("stds", [1.0] * 4)):
        out.append(f"    c.det.stds[{i}] = {_f(v)};\n")
    # ⚠️ 배경을 뺀 **의미상 클래스 수**다. softmax head(YOLACT)는 채널이 하나 더 많은데
    #    (cls_out_channels = nc+1) 그 폭은 `c.head.num_classes` 가 들고 간다 — 디코더는
    #    use_sigmoid 로 채널 폭을 스스로 계산한다(nc + (use_sigmoid?0:1)).
    out.append("    c.det.num_classes = "
               f"{int(cfg.get('num_classes_semantic', cfg.get('num_classes', 80)))};\n")
    out.append(f"    c.det.use_sigmoid = {str(bool(cfg.get('use_sigmoid', True))).lower()};\n")
    out.append(f"    c.det.ctr_clamp = {_f(cfg.get('ctr_clamp', 0.0))};\n")
    out.append(f"    c.det.score_voting = {str(bool(cfg.get('score_voting', False))).lower()};\n")
    out.append(f"    c.det.fast_nms = {str(bool(cfg.get('fast_nms', False))).lower()};\n")
    if cfg.get("nms_top_k"):
        out.append(f"    c.det.nms_top_k = {int(cfg['nms_top_k'])};\n")
    out.append("\n")

    for i, v in enumerate(cfg.get("img_mean", [0.0] * 3)):
        out.append(f"    c.img_mean[{i}] = {_f(v)};\n")
    for i, v in enumerate(cfg.get("img_std", [1.0] * 3)):
        out.append(f"    c.img_std[{i}] = {_f(v)};\n")
    out.append(f"    c.to_rgb = {str(bool(cfg.get('to_rgb', False))).lower()};\n")

    out.append("    return c;\n}\n\n}  // namespace visp\n")
    return "".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="mmdet_to_pt")
    ap.add_argument("--config", required=True, help="mmdet config .py")
    ap.add_argument("--checkpoint", default=None, help="가중치(.pth) — 없으면 config init")
    ap.add_argument("--out", required=True, help="출력 .pt")
    ap.add_argument("--size", type=int, default=512)
    # 텍스트 조건부 계열(GLIP)만 쓴다. 캡션이 고정이면 텍스트 임베딩이 상수라
    # 버퍼로 구워 그래프 입력을 이미지 하나로 만든다 — `MMDetTextCond` 주석 참고.
    ap.add_argument("--caption", default=None, help="텍스트 조건부 계열의 고정 문구")
    a = ap.parse_args(argv)

    m, shapes, cfg = build(a.config, a.checkpoint, a.size, caption=a.caption)
    print(f"  backbone/neck features: {shapes}")
    torch.save(m, a.out)
    n_head = sum(1 for k in m.state_dict() if k.startswith("bbox_head"))
    print(f"  → saved: {a.out}  (state_dict {len(m.state_dict())} tensors, head {n_head} 포함)")

    # 클래스는 `__module__`(= 'mmdet_wrap') 로 절여진다 → 로더가 그 이름을 import 할 수
    # 있어야 한다. `.pt` 옆에 같이 두면 환경변수 없이 열린다.
    for f in mmdet_compat.install_loader_modules(a.out, "mmdet_wrap"):
        print(f"  → loader module: {f}")

    # Decoding, anchor and head-conv configuration, emitted as a C++ function. Once the
    # architecture is fixed these are constants, so they are compiled into the runner.
    header = os.path.splitext(a.out)[0] + ".postproc.h"
    with open(header, "w") as f:
        f.write(emit_params(cfg, os.path.basename(a.config)))
    print(f"  → params: {header}  (head_type={cfg.get('head_type')})")


if __name__ == "__main__":
    main()
