#!/usr/bin/env python3
"""mmdet_to_pt.py — mmdet config → backbone/neck wrapped nn.Module → .pt 저장 (CLI).

전처리 단계(= "mmdet 을 파일로 뺀다"). g2c 와 무관하게 mmdet 만 여기(vision.cpp/tools/frontend/mmdet)서
다룬다. 클래스는 mmdet_wrap.MMDetBackbone → torch.load 가 동일 클래스로 복원(pickle 모듈명 =
'mmdet_wrap'). g2c 로 이 .pt 를 컴파일할 때도 이 폴더가 PYTHONPATH 에 있어야 mmdet_wrap 를 import 함.

사용:
  # (이 폴더 = vision.cpp/tools/frontend/mmdet 을 PYTHONPATH 에)
  python mmdet_to_pt.py --config retinanet_r18_fpn_1x_coco.py --out retinanet_bb.pt --size 512
  # 이후 g2c(코어 무수정, mmdet 코드 없음)로 컴파일:
  PYTHONPATH=<GTX_Compiler>:<이 폴더> g2c --model retinanet_bb.pt --name Retina --output output/retina
"""
import argparse
import os
import sys
import torch

# self-contained import: 이 파일 폴더(tools/frontend/mmdet)를 경로에 넣고 top-level 모듈로 import
# → torch.save 피클 모듈경로 = 'mmdet_wrap' (mmdet 라이브러리와 이름 충돌 없음).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mmdet_wrap import MMDetBackbone, build   # noqa: E402,F401 (MMDetBackbone: 피클 등록)


def _f(v):
    """C++ float 리터럴. repr 로 유효숫자를 보존한다 (0.1 이 0.1f 로 반올림되지 않게)."""
    return f"{float(v)!r}f"


def _arr(name, values):
    return f"    c.det.{name} = {{{', '.join(_f(v) for v in values)}}};\n"


def emit_params(cfg, config_name):
    """decode/anchor config → `mmdet_params()` 를 담은 C++ 헤더.
    """
    h = cfg.get("head_type", "raw")
    out = [
        "// Generated by mmdet_to_pt.py — do not edit.\n",
        f"// source: {config_name}\n",
        f"// head_type: {h}\n",
        "#pragma once\n\n",
        '#include "head.h"\n\n',
        "namespace visp {\n\n",
        "inline mmdet_cfg mmdet_params() {\n",
        "    mmdet_cfg c;\n",
    ]
    if h != "anchor":
        out += [
            "    // The head in this config was not recognised, so only the backbone is\n",
            "    // exported and decoding is left to the caller.\n",
            "    return c;\n}\n\n}  // namespace visp\n",
        ]
        return "".join(out)

    for k in ("stacked_convs", "feat_channels", "num_base", "num_classes"):
        if k in cfg:
            out.append(f"    c.head.{k} = {int(cfg[k])};\n")
    for k in ("cls_convs_prefix", "reg_convs_prefix", "cls_head", "reg_head"):
        if k in cfg:
            out.append(f'    c.head.{k} = "{cfg[k]}";\n')
    out.append(f"    c.head.head_has_norm = {str(bool(cfg.get('head_has_norm', False))).lower()};\n\n")

    out.append(_arr("strides", cfg["strides"]))
    out.append(_arr("octave_scales", cfg["octave_scales"]))
    out.append(_arr("ratios", cfg["ratios"]))
    out.append(f"    c.det.octave_base_scale = {_f(cfg.get('octave_base_scale', 4.0))};\n")
    out.append(f"    c.det.center_offset = {_f(cfg.get('center_offset', 0.0))};\n")
    for i, v in enumerate(cfg.get("means", [0.0] * 4)):
        out.append(f"    c.det.means[{i}] = {_f(v)};\n")
    for i, v in enumerate(cfg.get("stds", [1.0] * 4)):
        out.append(f"    c.det.stds[{i}] = {_f(v)};\n")
    out.append(f"    c.det.num_classes = {int(cfg.get('num_classes', 80))};\n")
    out.append(f"    c.det.use_sigmoid = {str(bool(cfg.get('use_sigmoid', True))).lower()};\n\n")

    for i, v in enumerate(cfg.get("img_mean", [0.0] * 3)):
        out.append(f"    c.img_mean[{i}] = {_f(v)};\n")
    for i, v in enumerate(cfg.get("img_std", [1.0] * 3)):
        out.append(f"    c.img_std[{i}] = {_f(v)};\n")
    out.append(f"    c.to_rgb = {str(bool(cfg.get('to_rgb', False))).lower()};\n")

    out.append("    return c;\n}\n\n}  // namespace visp\n")
    return "".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="mmdet_to_pt")
    ap.add_argument("--config", required=True, help="mmdet config .py")
    ap.add_argument("--checkpoint", default=None, help="가중치(.pth) — 없으면 config init")
    ap.add_argument("--out", required=True, help="출력 .pt")
    ap.add_argument("--size", type=int, default=512)
    a = ap.parse_args(argv)

    m, shapes, cfg = build(a.config, a.checkpoint, a.size)
    print(f"  backbone/neck features: {shapes}")
    torch.save(m, a.out)   # MMDetBackbone.__module__ == 'mmdet_wrap' → 어디서든 로드 가능
    n_head = sum(1 for k in m.state_dict() if k.startswith("bbox_head"))
    print(f"  → saved: {a.out}  (state_dict {len(m.state_dict())} tensors, head {n_head} 포함)")

    # decode/anchor + head-conv config → **C++ 함수**로 생성.
    # 모델이 정해지면 이 값들은 상수라 런타임에 읽을 이유가 없다 → 러너와 함께 컴파일한다.
    header = os.path.splitext(a.out)[0] + ".postproc.h"
    with open(header, "w") as f:
        f.write(emit_params(cfg, os.path.basename(a.config)))
    print(f"  → params: {header}  (head_type={cfg.get('head_type')})")


if __name__ == "__main__":
    main()
