#!/usr/bin/env python3
"""검증 결과(`results.json`)에서 문서 표를 **생성**한다. 손으로 옮기지 않는다.

    python tools/verify/make_status_table.py <results.json> [<results.json> ...]

왜 있나
------
문서의 계열 표를 사람이 옮겨 적으면 두 가지가 반드시 어긋난다.

1. **낡는다.** 계열이 열려도 표는 그대로다. 실측으로 `swin`·`grid_rcnn`·`detectors`·
   `seesaw_loss`·`guided_anchoring`·`cascade_rpn` 여섯이 이미 열린 뒤에도 문서는
   「남은 실패」에 그대로 두고 있었다 — 그걸 믿고 "남은 벽"을 보고했다.
2. **합계가 표와 안 맞는다.** 본문은 41+38 인데 표는 40+35 였다. 총합(86)이
   우연히 맞아떨어져 아무도 안 봤다.

그래서 **표는 사람이 쓰지 않는다.** 하네스가 낸 `results.json` 이 정본이고
이 스크립트가 그걸 마크다운으로 편다. 숫자를 고치고 싶으면 다시 재라.

⚠️ **판정을 여기서 바꾸지 않는다.** UNSUPPORTED 를 "예정"으로, FAIL 을 "경계"로
   부드럽게 만들지 마라 — 그러면 이 파일이 또 하나의 손문서가 된다.
"""
import json
import os
import sys
from collections import Counter


def load(paths):
    rows = {}
    for p in paths:
        for fam, verdict, note, secs in json.load(open(p)):
            # 같은 계열이 여러 파일에 있으면 **나중 파일이 이긴다** — 재측정이 최신이다.
            rows[fam] = (verdict, note, secs, os.path.basename(os.path.dirname(p)))
    return rows


def px_of(note):
    """비고에서 박스 오차만 뽑는다. 없으면 None."""
    for tok in (note or "").split():
        if tok.endswith("px"):
            try:
                return float(tok[:-2])
            except ValueError:
                return None
    return None


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    rows = load(sys.argv[1:])

    tally = Counter(v[0] for v in rows.values())
    print(f"<!-- GENERATED by tools/verify/make_status_table.py — 손으로 고치지 마라 -->")
    print(f"<!-- 계열 {len(rows)} · " +
          " · ".join(f"{k} {n}" for k, n in tally.most_common()) + " -->\n")

    passed = {f: v for f, v in rows.items() if v[0] == "PASS"}
    print(f"**{len(passed)} families agree on boxes.** "
          f"판정: 박스 2px · 점수 0.05 · 라벨 불일치 0 · 개수차 0.\n")
    print("| Family | Worst box | Detail |")
    print("| :--- | ---: | :--- |")
    for fam in sorted(passed, key=lambda f: (px_of(passed[f][1]) or 0.0)):
        note = passed[fam][1]
        px = px_of(note)
        print(f"| `{fam}` | {px:.2f} px | {note} |" if px is not None
              else f"| `{fam}` | — | {note} |")

    rest = {f: v for f, v in rows.items() if v[0] != "PASS"}
    if rest:
        print(f"\n**{len(rest)} do not.** 각각 사유가 있다 — 크래시도 조용한 오답도 아니다.\n")
        print("| Family | Verdict | Reason |")
        print("| :--- | :--- | :--- |")
        for fam in sorted(rest):
            verdict, note, _, _ = rest[fam]
            print(f"| `{fam}` | {verdict} | {note} |")

    # ⚠️ 합계를 **여기서** 찍는다. 본문이 표와 어긋나는 것을 막는 유일한 방법은
    #    둘을 같은 자리에서 내는 것이다.
    print(f"\n<!-- 합계 확인: PASS {len(passed)} + 그 외 {len(rest)} = {len(rows)} -->")
    return 0


if __name__ == "__main__":
    sys.exit(main())
