// GENERATED BY tools/install_arch.py — 손으로 고치지 마라(재설치하면 덮어쓴다).
//
// 이 파일은 **아무도 부르지 않는다.** 전역 객체 생성자가 프로그램 시작 시 스스로
// `arch_registry` 에 등록한다. 그래서 CLI 에 case 를 추가할 필요가 없다.
#include "visp/arch/Yolo26m.h"
#include "visp/arch_registry.h"

namespace {

visp::tensor forward(visp::model_ref m, visp::tensor x, visp::model_file const& f) {
    // `Yolo26m_params` 는 arch 마다 타입이 달라 레지스트리 시그니처에 못 싣는다 —
    // 여기서 만들어 소화한다.
    return visp::Yolo26m_forward(m, x, visp::Yolo26m_detect_params(f));
}

visp::arch_task make_task() {
    visp::arch_task t;
    t.kind = visp::arch_kind::detect_yolo;
    t.num_classes = 80;
    t.strides = {8.0f, 16.0f, 32.0f};
    t.nms_free = true;
    t.score_thr = 0.25f;
    t.input_size = 640;
    t.mean = {0.0f, 0.0f, 0.0f};
    t.stdv = {255.0f, 255.0f, 255.0f};
    t.class_names = {
        "person", "bicycle", "car", "motorcycle", "airplane", "bus",
        "train", "truck", "boat", "traffic light", "fire hydrant", "stop sign",
        "parking meter", "bench", "bird", "cat", "dog", "horse",
        "sheep", "cow", "elephant", "bear", "zebra", "giraffe",
        "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
        "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove",
        "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
        "fork", "knife", "spoon", "bowl", "banana", "apple",
        "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza",
        "donut", "cake", "chair", "couch", "potted plant", "bed",
        "dining table", "toilet", "tv", "laptop", "mouse", "remote",
        "keyboard", "cell phone", "microwave", "oven", "toaster", "sink",
        "refrigerator", "book", "clock", "vase", "scissors", "teddy bear",
        "hair drier", "toothbrush",
    };
    return t;
}

const visp::arch_registrar reg{"yolo26m", &forward, make_task()};

} // namespace
