// GENERATED BY SuperGate GTX Compiler (ggml/vision.cpp backend), DO NOT EDIT!
#pragma once
#include "visp/ml.h"

namespace visp {

struct Yolo26m_params {
    // TODO(ggml): 모델 하이퍼파라미터 (block_count 등)
};

tensor Yolo26m_forward(model_ref m, tensor x, Yolo26m_params const& p);
Yolo26m_params Yolo26m_detect_params(model_file const& f);

} // namespace visp
