#!/usr/bin/env python3
"""g2c 산출물을 vision.cpp 라이브러리에 붙인다 (arch 등록).

    python tools/install_arch.py <g2c_출력폴더> [--name Yolo26m] [--detect-yolo]

하는 일:
  1. `<Arch>.cpp` / `<Arch>.h` → `src/visp/arch/` 복사
  2. `<arch>_register.cpp` 생성 — 전역 객체가 스스로 레지스트리에 들어간다
  3. 끝. **CMake 는 안 건드린다** — `arch/*.cpp` 를 glob 으로 모은다.

왜 g2c 가 아니라 여기서 하나:
  g2c 는 main 의 source of truth 라 이 경로의 사정을 떠안기지 않는다. 그리고 검출
  파라미터(클래스 수·stride·NMS-free)는 **gguf 에 없다** — 여기서 채워 넣는다.

⚠️ 등록은 **공유 라이브러리 전제**다. static 으로 링크하면 아무도 참조하지 않는 전역
   객체를 링커가 버려 등록이 통째로 사라진다(`--whole-archive` 필요) → `DECISIONS.md`.
"""
import argparse
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VCPP = os.path.dirname(HERE)
ARCH_DIR = os.path.join(VCPP, "src", "visp", "arch")

COCO80 = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat",
    "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
    "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack",
    "umbrella", "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball",
    "kite", "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket",
    "bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple",
    "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair",
    "couch", "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse",
    "remote", "keyboard", "cell phone", "microwave", "oven", "toaster", "sink",
    "refrigerator", "book", "clock", "vase", "scissors", "teddy bear", "hair drier",
    "toothbrush",
]

REGISTER_TU = '''// GENERATED BY tools/install_arch.py — 손으로 고치지 마라(재설치하면 덮어쓴다).
//
// 이 파일은 **아무도 부르지 않는다.** 전역 객체 생성자가 프로그램 시작 시 스스로
// `arch_registry` 에 등록한다. 그래서 CLI 에 case 를 추가할 필요가 없다.
#include "visp/arch/{header}"
#include "visp/arch_registry.h"

namespace {{

visp::tensor forward(visp::model_ref m, visp::tensor x, visp::model_file const& f) {{
    // `{cls}_params` 는 arch 마다 타입이 달라 레지스트리 시그니처에 못 싣는다 —
    // 여기서 만들어 소화한다.
    return visp::{cls}_forward(m, x, visp::{cls}_detect_params(f));
}}

visp::arch_task make_task() {{
    visp::arch_task t;
{task_body}
    return t;
}}

const visp::arch_registrar reg{{"{arch}", &forward, make_task()}};

}} // namespace
'''


def find_outputs(out_dir, name):
    """생성 폴더에서 (클래스명, .cpp, .h) 를 찾는다."""
    cpps = [f for f in os.listdir(out_dir) if f.endswith(".cpp")]
    if name:
        cand = [f for f in cpps if os.path.splitext(f)[0] == name]
    else:
        cand = cpps
    if len(cand) != 1:
        sys.exit(f"오류: .cpp 를 하나로 못 좁혔다 ({cand}). --name 으로 지정할 것.")
    cls = os.path.splitext(cand[0])[0]
    h = os.path.join(out_dir, cls + ".h")
    if not os.path.exists(h):
        sys.exit(f"오류: 헤더가 없다: {h}")
    return cls, os.path.join(out_dir, cand[0]), h


def gguf_arch(out_dir, cls):
    """gguf 의 `general.architecture`. 이게 CLI 명령 이름이 된다.

    gguf 를 파싱하지 않고 **생성 .cpp 가 검증하는 문자열**에서 읽는다 — 어차피 둘이
    같아야 하고(안 맞으면 로드가 거부된다), 의존성도 안 는다.
    """
    src = open(os.path.join(out_dir, cls + ".cpp"), encoding="utf-8").read()
    m = re.search(r'arch\s*!=\s*"([^"]+)"', src)
    if not m:
        sys.exit("오류: 생성 .cpp 에서 general.architecture 를 못 찾았다")
    return m.group(1)


def detect_shapes(out_dir, cls):
    """생성 .cpp 의 출력 등록에서 (클래스 수, 앵커 수) 를 추정한다.

    `compute_graph_output(..., "out_i")` 앞의 텐서 shape 를 직접 읽을 수는 없으므로,
    **weights_manifest 의 마지막 conv 출력 채널**로 클래스 수를 잡는다. 실패하면 80.
    """
    nc = 80
    wt = os.path.join(out_dir, cls + ".weights.txt")
    if os.path.exists(wt):
        for line in open(wt, encoding="utf-8"):
            m = re.search(r"cv3.*?\[(\d+),", line)
            if m:
                nc = int(m.group(1))
    return nc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out_dir", help="g2c --output 폴더")
    ap.add_argument("--name", help="클래스명(예: Yolo26m). 생략하면 .cpp 가 하나일 때 자동")
    ap.add_argument("--detect-yolo", action="store_true",
                    help="YOLO dense 검출기로 등록(디코드+박스 그리기)")
    ap.add_argument("--classes", type=int, default=0, help="클래스 수(0=자동)")
    ap.add_argument("--strides", default="8,16,32")
    ap.add_argument("--size", type=int, default=640)
    ap.add_argument("--score-thr", type=float, default=0.25)
    ap.add_argument("--nms", action="store_true",
                    help="NMS 를 건다(기본은 NMS-free — YOLOv10/26 은 one2one 이라 필요 없다)")
    a = ap.parse_args()

    cls, cpp, hdr = find_outputs(a.out_dir, a.name)
    arch = gguf_arch(a.out_dir, cls)
    os.makedirs(ARCH_DIR, exist_ok=True)

    # 생성 .cpp 는 `#include "<cls>.h"` 가 아니라 상대 include 를 쓸 수 있다 → 헤더 이름을 맞춘다.
    header = cls + ".h"
    shutil.copy(cpp, os.path.join(ARCH_DIR, cls + ".cpp"))
    shutil.copy(hdr, os.path.join(ARCH_DIR, header))

    if a.detect_yolo:
        nc = a.classes or detect_shapes(a.out_dir, cls)
        strides = [s.strip() for s in a.strides.split(",") if s.strip()]
        names = COCO80 if nc == 80 else []
        body = [
            "    t.kind = visp::arch_kind::detect_yolo;",
            f"    t.num_classes = {nc};",
            "    t.strides = {" + ", ".join(f"{s}.0f" for s in strides) + "};",
            f"    t.nms_free = {'false' if a.nms else 'true'};",
            f"    t.score_thr = {a.score_thr}f;",
            f"    t.input_size = {a.size};",
        ]
        if names:
            body.append("    t.class_names = {")
            for i in range(0, len(names), 6):
                body.append("        " + ", ".join(f'"{n}"' for n in names[i:i + 6]) + ",")
            body.append("    };")
    else:
        body = ["    t.kind = visp::arch_kind::raw;"]

    reg_path = os.path.join(ARCH_DIR, arch + "_register.cpp")
    with open(reg_path, "w", encoding="utf-8") as f:
        f.write(REGISTER_TU.format(header=header, cls=cls, arch=arch,
                                   task_body="\n".join(body)))

    print(f"설치 완료: {cls} → arch '{arch}'")
    print(f"  {ARCH_DIR}/{cls}.cpp")
    print(f"  {ARCH_DIR}/{header}")
    print(f"  {reg_path}")
    print()
    print("다음:")
    print(f"  cmake --build {os.path.join(VCPP, 'build')} -j4")
    print(f"  {os.path.join(VCPP, 'build/bin/vision-cli')} {arch} -m <gguf> -i <img> -o out.jpg")


if __name__ == "__main__":
    main()
