#!/usr/bin/env python3
"""g2c 산출물을 vision.cpp 라이브러리에 붙인다 (arch 등록).

    python tools/install_arch.py <g2c_출력폴더> [--name Yolo26m] [--detect-yolo]

하는 일:
  1. `<Arch>.cpp` / `<Arch>.h` → `src/visp/arch/` 복사
  2. `<arch>_register.cpp` 생성 — 전역 객체가 스스로 레지스트리에 들어간다
  3. 끝. **CMake 는 안 건드린다** — `arch/*.cpp` 를 glob 으로 모은다.

왜 g2c 가 아니라 여기서 하나:
  g2c 는 main 의 source of truth 라 이 경로의 사정을 떠안기지 않는다. 그리고 검출
  파라미터(클래스 수·stride·NMS-free)는 **gguf 에 없다** — 여기서 채워 넣는다.

⚠️ 등록은 **공유 라이브러리 전제**다. static 으로 링크하면 아무도 참조하지 않는 전역
   객체를 링커가 버려 등록이 통째로 사라진다(`--whole-archive` 필요) → `DECISIONS.md`.
"""
import argparse
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
VCPP = os.path.dirname(HERE)
ARCH_DIR = os.path.join(VCPP, "src", "visp", "arch")

COCO80 = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat",
    "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
    "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack",
    "umbrella", "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball",
    "kite", "baseball bat", "baseball glove", "skateboard", "surfboard", "tennis racket",
    "bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple",
    "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair",
    "couch", "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse",
    "remote", "keyboard", "cell phone", "microwave", "oven", "toaster", "sink",
    "refrigerator", "book", "clock", "vase", "scissors", "teddy bear", "hair drier",
    "toothbrush",
]

REGISTER_TU = '''// GENERATED BY tools/install_arch.py — 손으로 고치지 마라(재설치하면 덮어쓴다).
//
// 이 파일은 **아무도 부르지 않는다.** 전역 객체 생성자가 프로그램 시작 시 스스로
// `arch_registry` 에 등록한다. 그래서 CLI 에 case 를 추가할 필요가 없다.
#include "visp/arch/{header}"
#include "visp/arch_registry.h"

namespace {{

visp::tensor forward(visp::model_ref m, visp::tensor x, visp::model_file const& f) {{
    // `{cls}_params` 는 arch 마다 타입이 달라 레지스트리 시그니처에 못 싣는다 —
    // 여기서 만들어 소화한다.
    return visp::{cls}_forward(m, x, visp::{cls}_detect_params(f));
}}

visp::arch_task make_task() {{
    visp::arch_task t;
{task_body}
    return t;
}}

const visp::arch_registrar reg{{"{arch}", &forward, make_task()}};

}} // namespace
'''


def find_outputs(out_dir, name):
    """생성 폴더에서 (클래스명, .cpp, .h) 를 찾는다."""
    cpps = [f for f in os.listdir(out_dir) if f.endswith(".cpp")]
    if name:
        cand = [f for f in cpps if os.path.splitext(f)[0] == name]
    else:
        cand = cpps
    if len(cand) != 1:
        sys.exit(f"error: cannot tell which .cpp to install ({cand}). Name it with --name.")
    cls = os.path.splitext(cand[0])[0]
    h = os.path.join(out_dir, cls + ".h")
    if not os.path.exists(h):
        sys.exit(f"error: header not found: {h}")
    return cls, os.path.join(out_dir, cand[0]), h


def gguf_arch(out_dir, cls):
    """gguf 의 `general.architecture`. 이게 CLI 명령 이름이 된다.

    gguf 를 파싱하지 않고 **생성 .cpp 가 검증하는 문자열**에서 읽는다 — 어차피 둘이
    같아야 하고(안 맞으면 로드가 거부된다), 의존성도 안 는다.
    """
    src = open(os.path.join(out_dir, cls + ".cpp"), encoding="utf-8").read()
    m = re.search(r'arch\s*!=\s*"([^"]+)"', src)
    if not m:
        sys.exit("error: the generated .cpp declares no general.architecture")
    return m.group(1)


def detect_shapes(out_dir, cls):
    r"""생성 `<cls>.py` 에서 탐지 헤드의 클래스 수를 읽는다. 못 읽으면 80.

    ⚠️ **예전엔 `<cls>.weights.txt` 에서 `cv3.*\[(\d+),` 를 찾았는데 그 파일에는
       shape 대괄호가 없다** — 순수 텐서 이름만 있다. 정규식이 **한 번도 안 맞아서**
       언제나 80 으로 조용히 떨어졌다(2026-09-01 실측). COCO 모델은 우연히 맞았고
       커스텀 클래스 수 모델은 조용히 틀렸다.

       생성 `.py` 에는 `out_channels=` 가 주석의 모듈 경로와 함께 남는다. 탐지 헤드
       (`Detect[...]`) 안의 마지막 `cv3` conv 출력 채널이 클래스 수다.
    """
    py = os.path.join(out_dir, cls + ".py")
    if not os.path.exists(py):
        print(f"  ⚠ {cls}.py 가 없다 — 클래스 수를 80 으로 둔다. 다르면 --classes 로 줘라")
        return 80
    nc = None
    for line in open(py, encoding="utf-8"):
        if "CONV2D" not in line or "Detect[" not in line or "cv3" not in line:
            continue
        m = re.search(r"out_channels=(\d+)", line)
        if m:
            nc = int(m.group(1))
    if nc is None:
        print(f"  ⚠ {cls}.py 에서 탐지 헤드를 못 찾았다 — 80 으로 둔다. "
              f"다르면 --classes 로 줘라")
        return 80
    return nc


def traced_size(out_dir, cls, fallback):
    """생성 `<Arch>.py` 에서 trace 입력 크기를 읽는다.

    그래프는 **한 크기로만** 돈다(trace 가 그 크기를 구웠다). 러너가 다른 크기로 돌리면
    `GGML_ASSERT(ggml_nelements(a) == ne0*ne1)` 로 죽는다 — 사람이 `--size` 를 기억하게
    두지 말고 산출물에서 읽는다.
    """
    path = os.path.join(out_dir, cls + ".py")
    try:
        src = open(path, encoding="utf-8").read()
    except OSError:
        return fallback, fallback
    m = re.search(r"np\.random\.randn\(\s*\d+\s*,\s*\d+\s*,\s*(\d+)\s*,\s*(\d+)", src)
    if not m:
        return fallback, fallback
    h, w = int(m.group(1)), int(m.group(2))
    if h != w:
        print(f"  · 입력이 정사각이 아니다 — {h}x{w} 를 그대로 등록한다")
    return h, w



def load_meta(out_dir, cls):
    """`<cls>.meta.json` — g2c 가 컴파일 때 남긴 값. 없으면 빈 dict.

    mean/std·검출기 종류·클래스 수는 **gguf 에 없다.** 컴파일 시점에는 원본 모델이
    있으니 g2c 가 아는 것만 적어 둔다. 여기서 그것을 **기본값으로** 쓴다 —
    **명령줄로 준 값이 언제나 이긴다.**
    """
    path = os.path.join(out_dir, cls + ".meta.json")
    if not os.path.exists(path):
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            meta = json.load(f)
    except Exception as e:                       # noqa: BLE001
        print(f"  ⚠ {path} 를 못 읽었다({e}) — 손으로 준 값만 쓴다")
        return {}
    known = ", ".join(k for k in ("mean", "std", "kind", "classes") if k in meta)
    print(f"  · meta 사용: {path}" + (f" ({known})" if known else " (아는 값 없음)"))
    return meta


def _fmt3(v, fallback):
    if not isinstance(v, (list, tuple)) or len(v) != 3:
        return fallback
    return ",".join(str(float(x)) for x in v)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out_dir", help="g2c --output 폴더")
    ap.add_argument("--name", help="클래스명(예: Yolo26m). 생략하면 .cpp 가 하나일 때 자동")
    ap.add_argument("--detect-yolo", action="store_true",
                    help="YOLO dense 검출기로 등록(디코드+박스 그리기). "
                         "meta.json 에 kind=detect_yolo 면 안 줘도 켜진다")
    ap.add_argument("--classes", type=int, default=0, help="클래스 수(0=자동)")
    ap.add_argument("--strides", default=None)
    ap.add_argument("--size", type=int, default=0,
                    help="입력 해상도. 생략하면 생성 <Arch>.py 에서 읽는다")
    ap.add_argument("--mean", default=None,
                    help="전처리 평균(픽셀 0~255 기준). 생략하면 meta.json → 없으면 0,0,0. "
                         "torchvision 분류기는 '123.675,116.28,103.53'")
    ap.add_argument("--std", default=None,
                    help="전처리 표준편차. 생략하면 meta.json → 없으면 255,255,255")
    ap.add_argument("--score-thr", type=float, default=0.25)
    ap.add_argument("--nms", action="store_true",
                    help="NMS 를 건다(기본은 NMS-free — YOLOv10/26 은 one2one 이라 필요 없다)")
    a = ap.parse_args()

    cls, cpp, hdr = find_outputs(a.out_dir, a.name)
    arch = gguf_arch(a.out_dir, cls)

    # 우선순위: 명령줄 > meta.json > 옛 기본값
    meta = load_meta(a.out_dir, cls)
    a.mean = a.mean or _fmt3(meta.get("mean"), "0,0,0")
    a.std = a.std or _fmt3(meta.get("std"), "255,255,255")
    a.strides = a.strides or ",".join(str(int(x)) for x in meta.get("strides", [8, 16, 32]))
    if not a.detect_yolo and meta.get("kind") == "detect_yolo":
        a.detect_yolo = True
    if not a.classes and isinstance(meta.get("classes"), int):
        a.classes = meta["classes"]
    os.makedirs(ARCH_DIR, exist_ok=True)

    # 생성 .cpp 는 `#include "<cls>.h"` 가 아니라 상대 include 를 쓸 수 있다 → 헤더 이름을 맞춘다.
    header = cls + ".h"
    shutil.copy(cpp, os.path.join(ARCH_DIR, cls + ".cpp"))
    shutil.copy(hdr, os.path.join(ARCH_DIR, header))

    ih, iw = traced_size(a.out_dir, cls, 640)
    if a.size:
        ih = iw = a.size
    size = ih  # 옛 필드 호환 — 정사각이면 이 값 하나로 충분하다

    def _triple(spec, what):
        v = [x.strip() for x in spec.split(",") if x.strip()]
        if len(v) != 3:
            sys.exit(f"error: --{what} takes three values, got: {spec}")
        return "{" + ", ".join(f"{float(x)}f" for x in v) + "}"

    norm = [f"    t.mean = {_triple(a.mean, 'mean')};",
            f"    t.stdv = {_triple(a.std, 'std')};"]

    if a.detect_yolo:
        nc = a.classes or detect_shapes(a.out_dir, cls)
        strides = [s.strip() for s in a.strides.split(",") if s.strip()]
        names = COCO80 if nc == 80 else []
        body = [
            "    t.kind = visp::arch_kind::detect_yolo;",
            f"    t.num_classes = {nc};",
            "    t.strides = {" + ", ".join(f"{s}.0f" for s in strides) + "};",
            f"    t.nms_free = {'false' if a.nms else 'true'};",
            f"    t.score_thr = {a.score_thr}f;",
            f"    t.input_size = {size};",
            f"    t.input_w = {iw};",
            f"    t.input_h = {ih};",
        ] + norm
        if names:
            body.append("    t.class_names = {")
            for i in range(0, len(names), 6):
                body.append("        " + ", ".join(f'"{n}"' for n in names[i:i + 6]) + ",")
            body.append("    };")
    else:
        # 검출기가 아니어도 크기는 실어야 한다 — 러너가 그 크기로 입력을 만든다.
        body = ["    t.kind = visp::arch_kind::raw;",
                f"    t.input_size = {size};",
                f"    t.input_w = {iw};",
                f"    t.input_h = {ih};"] + norm

    reg_path = os.path.join(ARCH_DIR, arch + "_register.cpp")
    with open(reg_path, "w", encoding="utf-8") as f:
        f.write(REGISTER_TU.format(header=header, cls=cls, arch=arch,
                                   task_body="\n".join(body)))

    print(f"설치 완료: {cls} → arch '{arch}'")
    print(f"  {ARCH_DIR}/{cls}.cpp")
    print(f"  {ARCH_DIR}/{header}")
    print(f"  {reg_path}")
    print()
    print("next:")
    print(f"  cmake --build {os.path.join(VCPP, 'build')} -j4")
    # vision-cli 는 확장자와 무관하게 PNG 를 쓴다(image_save → stbi_write_png).
    # .jpg 를 권하면 PNG 인데 이름만 .jpg 인 파일이 나와 뷰어가 거부한다.
    print(f"  {os.path.join(VCPP, 'build/bin/vision-cli')} {arch} -m <gguf> -i <img> -o out.png")


if __name__ == "__main__":
    main()
